% Estimate the area of a quarter circle by the Monte Carlo method
%The Monte Carlo's method generates points in the plane and the idea is to calculate
% the area with the proportion of points that lies within an area given by equation such as the circunference.
% The area will be A = p*a*b 
% Where each variable represents:
% p = proportion of points that is under the area of interest (x^2  + y^2 = 1 in this case)
% a, b = size of rectangle where we generated points uniformly

%We will see the average of each sample.
M = 20; %No. rows
N = 100; % No. cols
K = 100; %Change the number of points generated by this factor each time
A = zeros(M,N);
p = 0.4;
for j = 1:N
    for i = 1:M
        x= rand(1,j*K);
        y= rand(1,j*K);
        A(i,j) = sum(x.*x + y.*y <= 1);
    end
    A(:,j) = A(:,j)/(j*K);
end
hold on;
title('Aproximación de 1/4 del área de un círculo de radio 1');
xlabel('Número de puntos');
ylabel('Valor de las medias');

plot(K*(1:N),A','+')
plot(K*(1:N),mean(A),'k')
plot(K*(1:N),std(A)+mean(A),'k')
plot(K*(1:N),-std(A)+mean(A),'k')
pause(5);

hold off
plot(K*(1:N),std(A),'+b');

